In [1]:
from __future__ import unicode_literals

import pandas as pd
import numpy as np

In [5]:
wind_speed_28w_df = pd.read_csv('../../../../data/raw/FincaPorvenir/Metereologico/28-weeks_January-12_August-03_2018/' \
                                 'Velocidad-del-viento_January-12_August-03_2018.csv', )

In [6]:
print(wind_speed_28w_df.shape)
wind_speed_28w_df.head()

(9752, 2)

                Fecha:  Velocidad del viento (Km/h)
0  2018-01-12 00:17:28                          0.0
1  2018-01-12 00:47:28                          0.0
2  2018-01-12 01:17:27                          0.0
3  2018-01-12 01:47:27                          0.0
4  2018-01-12 02:17:28                          0.0

In [8]:
# We turn to datetime the Fecha column values 
# https://pandas.pydata.org/pandas-docs/version/0.20/generated/pandas.to_datetime.html
wind_speed_28w_df['Fecha:'] = pd.to_datetime(wind_speed_28w_df['Fecha:'])

# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.groupby.html?highlight=groupby#pandas.DataFrame.groupby
# https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Grouper.html
# We group the dataframe wind_speed_28w_df the column Fecha: (se la decimos con Grouper)
# with a frecuency of D calendar days generating to each day the wind speed average value
wind_speed_28w_average_per_day = (wind_speed_28w_df.groupby(pd.Grouper(key='Fecha:', freq='D'))['Velocidad del viento (Km/h)'].mean().reset_index())

In [9]:
print(wind_speed_28w_average_per_day.shape)
wind_speed_28w_average_per_day

(204, 2)

        Fecha:  Velocidad del viento (Km/h)
0   2018-01-12                     1.182682
1   2018-01-13                     0.904328
2   2018-01-14                     1.724738
3   2018-01-15                     1.259122
4   2018-01-16                     1.392441
5   2018-01-17                     1.231798
6   2018-01-18                     0.805282
7   2018-01-19                     0.975887
8   2018-01-20                     0.893306
9   2018-01-21                     2.693156
10  2018-01-22                     1.813427
11  2018-01-23                     0.740679
12  2018-01-24                     2.332362
13  2018-01-25                     3.153937
14  2018-01-26                     3.623844
15  2018-01-27                     2.884289
16  2018-01-28                     3.422492
17  2018-01-29                     3.343767
18  2018-01-30                     4.680419
19  2018-01-31                     4.959295
20  2018-02-01                     4.459820
21  2018-02-02                     4.709010
22  2018-02-03                     4.747014
23  2018-02-04                     3.908162
24  2018-02-05                     5.088727
25  2018-02-06                     4.841634
26  2018-02-07                     4.073157
27  2018-02-08                     4.625360
28  2018-02-09                     4.038796
29  2018-02-10                     2.622609
..         ...                          ...
174 2018-07-05                     1.683078
175 2018-07-06                     1.462749
176 2018-07-07                     1.184720
177 2018-07-08                     2.547550
178 2018-07-09                     1.363577
179 2018-07-10                     0.704151
180 2018-07-11                     1.286182
181 2018-07-12                     2.299043
182 2018-07-13                     1.719602
183 2018-07-14                     1.468008
184 2018-07-15                     1.452134
185 2018-07-16                     0.464923
186 2018-07-17                     1.513682
187 2018-07-18                     0.847447
188 2018-07-19                     2.572695
189 2018-07-20                     1.473043
190 2018-07-21                     1.513964
191 2018-07-22                     1.155384
192 2018-07-23                     1.375446
193 2018-07-24                     1.232876
194 2018-07-25                     1.210633
195 2018-07-26                     1.423534
196 2018-07-27                     2.118439
197 2018-07-28                     0.957073
198 2018-07-29                     1.385828
199 2018-07-30                     2.052338
200 2018-07-31                     1.400377
201 2018-08-01                     1.167884
202 2018-08-02                     0.757902
203 2018-08-03                     1.823858

[204 rows x 2 columns]

In [11]:
# We export the wind_speed_28w_average_per_day dataframe to .csv file
wind_speed_28w_average_per_day.to_csv('../../../../data/interim/WindSpeed/28-weeks_January-12_August-03_2018/' +'\n' 
                                  'Wind-Speed_Average_per-day_January-12_August-03.csv', sep=',', header=True, index=False)